import React from "react";

export default function settings() {
    return (
    <>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec nunc</p>
    </>
    )
};
